#!/usr/bin/env bash 

if [[ $# -eq 0 ]]; then 
    echo -e "ERROR: No arguments specified.\nExiting..."
    exit
fi

if [[ $OSTYPE == "darwin"* ]]; then 
    toSC=/Applications/SuperCollider.app/Contents/MacOS/sclang
    if [[ ! -e $toSC  ]]; then 
        echo "WARNING: SuperCollider is not properly installed."
        echo "Download SuperCollider at https://supercollider.github.io"
        echo "Then install it in your Applications folder"
        exit 
    fi
else if [[ $OSTYPE == "linux-gnu"* ]]; then 
    toSC=$(which sclang)
    if [[ -z $toSC ]]; then 
        echo "WARNING: SuperCollider is not properly installed"
        echo "Download SuperCollider at https://supercollider.github.io"
        echo "Then follow the installation instructions for your distro"
    fi
else 
    echo "WARNING: $OSTYPE not supported"
    echo "Exiting..."
    exit
fi 

# Feed argument to sclang
$toSC $1 $1
